language: generic
sudo: required
services:
  - docker

before-install:
  - docker build -t kmerdzhanov/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kmerdzhanov/docker-react npm run test